### ISSUE TITLE
[BUG] Not working

### ISSUE THREAD

**Issue by KendallDoesCoding** [divyakelaskar/music-player#1]
CONSOLE LOG:
```
Uncaught TypeError: Cannot set properties of null (setting 'src')
    at loadSong (app.js:21:13)
    at app.js:17:1
```

**Comment by divyakelaskar** [comment]
The app isn't complete yet. This one of my many ~incomplete~ side projects.

**Comment by KendallDoesCoding** [comment]
> The app isn't complete yet. This one of my many ~incomplete~ side projects.

Ok ok, I suggest you mention the project is incomplete in the README.md then :)!
