### ISSUE TITLE
[QnA] Tutorial?

### ISSUE THREAD

**Issue by KendallDoesCoding** [divyakelaskar/music-player#2]
I think Traversy Media or someone put a tutorial on this, did you follow that tutorial for this project or did you code it yourself?

**Comment by divyakelaskar** [comment]
Yeah, I followed along the Traversy Media tutorial for this one.

**Comment by KendallDoesCoding** [comment]
> Yeah, I followed along the Traversy Media tutorial for this one.

Ok cool!
